[package]
name = "opaque-debug"
version = "0.3.0" # Also update html_root_url in lib.rs when bumping this
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Macro for opaque Debug trait implementation"
documentation = "https://docs.rs/opaque-debug"
repository = "https://github.com/RustCrypto/utils"
edition = "2018"
 [dependencies] 
 sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
 
 [features]
 default = []
 mesalock_sgx = ["sgx_tstd"]